---
abstract: 'find out how a piece of code expects to be called'
author:
  - 'Tom Molesworth <TEAM@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::CheckDeps: '0.010'
  Test::More: '0.94'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.024, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-Signature-Arity
no_index:
  directory:
    - eg
    - share
    - shares
    - t
    - xt
provides:
  Acme::Signature::Arity:
    file: lib/Acme/Signature/Arity.pm
    version: '0.003'
requires:
  B: '0'
  List::Util: '0'
  experimental: '0'
  perl: '5.026'
resources:
  bugtracker: https://github.com/team-at-cpan/Acme-Signature-Arity/issues
  homepage: https://github.com/team-at-cpan/Acme-Signature-Arity
  repository: https://github.com/team-at-cpan/Acme-Signature-Arity.git
version: '0.003'
x_authority: cpan:TEAM
x_generated_by_perl: v5.34.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
